name: Build Docker image

on:
  workflow_dispatch:
  #push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push (sonar-scan)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: bdd_automation/Dockerfile-sonar
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sonar-scan-bdd-automation:v0.0.1